version: "3.0"
services:
  drone-app:
    build: .
    restart: always
    links:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://db:5432/musala
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - spring.profiles.active=test
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=musala
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432